/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as RegisterAdminRouteImport } from './routes/register-admin'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as MySchoolRouteImport } from './routes/my-school'
import { Route as ManageStudentsRouteImport } from './routes/manage-students'
import { Route as ManageSchoolsRouteImport } from './routes/manage-schools'
import { Route as ManageRolesRouteImport } from './routes/manage-roles'
import { Route as ManageBatchesRouteImport } from './routes/manage-batches'
import { Route as ManageAdminsRouteImport } from './routes/manage-admins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAdminRoute = RegisterAdminRouteImport.update({
  id: '/register-admin',
  path: '/register-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const MySchoolRoute = MySchoolRouteImport.update({
  id: '/my-school',
  path: '/my-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageStudentsRoute = ManageStudentsRouteImport.update({
  id: '/manage-students',
  path: '/manage-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSchoolsRoute = ManageSchoolsRouteImport.update({
  id: '/manage-schools',
  path: '/manage-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRolesRoute = ManageRolesRouteImport.update({
  id: '/manage-roles',
  path: '/manage-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBatchesRoute = ManageBatchesRouteImport.update({
  id: '/manage-batches',
  path: '/manage-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminsRoute = ManageAdminsRouteImport.update({
  id: '/manage-admins',
  path: '/manage-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manage-admins': typeof ManageAdminsRoute
  '/manage-batches': typeof ManageBatchesRoute
  '/manage-roles': typeof ManageRolesRoute
  '/manage-schools': typeof ManageSchoolsRoute
  '/manage-students': typeof ManageStudentsRoute
  '/my-school': typeof MySchoolRoute
  '/no-access': typeof NoAccessRoute
  '/register-admin': typeof RegisterAdminRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manage-admins': typeof ManageAdminsRoute
  '/manage-batches': typeof ManageBatchesRoute
  '/manage-roles': typeof ManageRolesRoute
  '/manage-schools': typeof ManageSchoolsRoute
  '/manage-students': typeof ManageStudentsRoute
  '/my-school': typeof MySchoolRoute
  '/no-access': typeof NoAccessRoute
  '/register-admin': typeof RegisterAdminRoute
  '/test': typeof TestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manage-admins': typeof ManageAdminsRoute
  '/manage-batches': typeof ManageBatchesRoute
  '/manage-roles': typeof ManageRolesRoute
  '/manage-schools': typeof ManageSchoolsRoute
  '/manage-students': typeof ManageStudentsRoute
  '/my-school': typeof MySchoolRoute
  '/no-access': typeof NoAccessRoute
  '/register-admin': typeof RegisterAdminRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/manage-admins'
    | '/manage-batches'
    | '/manage-roles'
    | '/manage-schools'
    | '/manage-students'
    | '/my-school'
    | '/no-access'
    | '/register-admin'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/manage-admins'
    | '/manage-batches'
    | '/manage-roles'
    | '/manage-schools'
    | '/manage-students'
    | '/my-school'
    | '/no-access'
    | '/register-admin'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/manage-admins'
    | '/manage-batches'
    | '/manage-roles'
    | '/manage-schools'
    | '/manage-students'
    | '/my-school'
    | '/no-access'
    | '/register-admin'
    | '/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ManageAdminsRoute: typeof ManageAdminsRoute
  ManageBatchesRoute: typeof ManageBatchesRoute
  ManageRolesRoute: typeof ManageRolesRoute
  ManageSchoolsRoute: typeof ManageSchoolsRoute
  ManageStudentsRoute: typeof ManageStudentsRoute
  MySchoolRoute: typeof MySchoolRoute
  NoAccessRoute: typeof NoAccessRoute
  RegisterAdminRoute: typeof RegisterAdminRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-admin': {
      id: '/register-admin'
      path: '/register-admin'
      fullPath: '/register-admin'
      preLoaderRoute: typeof RegisterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-school': {
      id: '/my-school'
      path: '/my-school'
      fullPath: '/my-school'
      preLoaderRoute: typeof MySchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-students': {
      id: '/manage-students'
      path: '/manage-students'
      fullPath: '/manage-students'
      preLoaderRoute: typeof ManageStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-schools': {
      id: '/manage-schools'
      path: '/manage-schools'
      fullPath: '/manage-schools'
      preLoaderRoute: typeof ManageSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-roles': {
      id: '/manage-roles'
      path: '/manage-roles'
      fullPath: '/manage-roles'
      preLoaderRoute: typeof ManageRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-batches': {
      id: '/manage-batches'
      path: '/manage-batches'
      fullPath: '/manage-batches'
      preLoaderRoute: typeof ManageBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-admins': {
      id: '/manage-admins'
      path: '/manage-admins'
      fullPath: '/manage-admins'
      preLoaderRoute: typeof ManageAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ManageAdminsRoute: ManageAdminsRoute,
  ManageBatchesRoute: ManageBatchesRoute,
  ManageRolesRoute: ManageRolesRoute,
  ManageSchoolsRoute: ManageSchoolsRoute,
  ManageStudentsRoute: ManageStudentsRoute,
  MySchoolRoute: MySchoolRoute,
  NoAccessRoute: NoAccessRoute,
  RegisterAdminRoute: RegisterAdminRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
